### ISSUE TITLE
app crashes on update of react-native-reanimated version 1.5.0

### ISSUE THREAD

**Issue by panda0603** [computerjazz/react-native-draggable-flatlist#122]
just updated react-native-reanimated to 1.5.0 from 1.4.0, 

app crashes while using the draggable-flatlist component. 

release doc for 1.5.0 says there is no breaking change, 

but crash is there. Please have a look.

roled back down to 1.4.0 for now.

**Comment by computerjazz** [comment]
looks like there was a bug in 1.5 that may be responsible -- try 1.6?
https://github.com/software-mansion/react-native-reanimated/releases

**Comment by panda0603** [comment]
@computerjazz just tried 1.6.0, still same bug :( One warning and One error. Warning was about maximum call stack.

**Comment by baughmann** [comment]
@computerjazz @panda0603 Getting the same warning. I've attached the error you get when debugging.

I normally get this error when I change some native module function/property without updating my JS side, and since this package doesn't have a corresponding native module, it sounds to me like 1.5 actually is a breaking change?

<img width="343" alt="Screen Shot 2020-01-15 at 9 02 54 PM" src="https://user-images.githubusercontent.com/6177411/72487060-c4a88c80-37da-11ea-8009-6d3f76aa5ebc.png">

**Comment by baughmann** [comment]
@panda0603 @computerjazz Upon further testing I can confirm that I can get it to work for me when I lock `react-native-reanimated` to 1.4.0

**Comment by computerjazz** [comment]
Thanks, opened an issue on react-native-reanimated and will try to debug on my end. 
https://github.com/software-mansion/react-native-reanimated/issues/557

**Comment by computerjazz** [comment]
Should be fixed, please install latest and let me know!

**Comment by panda0603** [comment]
@computerjazz confirmed to be fixed in 2.0.14. Thanks!

**Comment by vanhungoz** [comment]
it is not work for me, still crash with log:"Exception thrown while executing UI block: 'node' is a required parameter"

**Comment by panda0603** [comment]
@computerjazz @vanhungoz actually, while some of the other errors are fixed, it still crashes like vanhungoz replied.

**Comment by panda0603** [comment]
<img width="302" alt="image" src="https://user-images.githubusercontent.com/34116285/72519151-27149200-389a-11ea-9283-40e99242b256.png">
this is the error on android.

**Comment by computerjazz** [comment]
Is this an android-only crash now? If so can you try installing reanimated off master and see if that fixes it?

There was some activity yesterday that looks related: https://github.com/software-mansion/react-native-reanimated/issues/559

**Comment by computerjazz** [comment]
er, actually this one looks even more related 😅: https://github.com/software-mansion/react-native-reanimated/issues/555

**Comment by computerjazz** [comment]
Regression ticket with these issues has been opened on reanimated: https://github.com/software-mansion/react-native-reanimated/issues/561

**Comment by computerjazz** [comment]
reanimated 1.7 released with fixes -- anyone want to give it a test? @panda0603 @baughmann

**Comment by baughmann** [comment]
@computerjazz Appears to be working on iOS 👍

**Comment by panda0603** [comment]
@computerjazz Just tried 1.7.0, no issues so far for both IOS and Android. Will report if any issues occur. Thanks for the care :)
