### ISSUE TITLE
Prop `extraData` is ignored

### ISSUE THREAD

**Issue by vranjesluka** [computerjazz/react-native-draggable-flatlist#290]
**Describe the bug**
The `extraData` prop is ignored when passed to the DraggableFlatList

**To Reproduce**
Sorry no link, I was trying to do something like this:  
``` tsx
  const [selectedIndex, setSelectedIndex] = useState<number | undefined>(undefined);

  return (
        <DraggableFlatList
          data={data}
          renderItem={renderItem}
          containerStyle={styles.draggableContainer}
          keyExtractor={(item, index): string =>
            `draggable-item-${item != null ? item.id : index}`
          }
          onDragEnd={({ data }): void => setActiveData(data)}
          extraData={selectedIndex}
        />
    )
```

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: Both
 - React Native or Expo version: 0.63.0
 - Reanimated version: x
 - React Native Gesture Handler version: x

**Additional context**
I think the line index.tsx:1060 is to blame.  
``` tsx
<AnimatedFlatList
            {...this.props}
            CellRendererComponent={this.CellRendererComponent}
            ref={this.flatlistRef}
            onContentSizeChange={this.onListContentSizeChange}
            scrollEnabled={!hoverComponent && scrollEnabled}
            renderItem={this.renderItem}
            extraData={this.state}
            keyExtractor={this.keyExtractor}
            onScroll={this.onScroll}
            scrollEventThrottle={1}
            simultaneousHandlers={simultaneousHandlers}
          />
```
It overrides the passed props. The line should probably combine the `this.props.extraData` and `this.state`. 
I hope this helps, I'm unable currently to contribute more. 

The walkaround we use is to combine `extraData` (e.g. `selectedIndex`) into `data` directly.

**Comment by vranjesluka** [comment]
Actually, there is an easier and better walkaround:
https://snack.expo.io/FSOz9JBrW

Using the dependency in `UseCallback` for the renderItem.
Feel free to close the issue if that is the preferred way of using and adding extra data.

**Comment by computerjazz** [comment]
should be fixed in current version

**Comment by gummihuhn0** [comment]
I updated to version 3.0.5, but extraData is still not working:

        <DraggableFlatList
          data={ this.state.data }
          renderItem={ this.renderItem }
          keyExtractor={(item, index) => `draggable-item-${item.id-index}`}
          scrollPercent={5}
          onDragEnd={({ data }) => this.onDragEnd(data)}
          extraData={this.state.refresh}
        />

refresh state will be updated when user changes the style of the list (short, detail, etc.) by pressing a button. using the same code, but switching to FlatList - extraData will be recognized.

Platform: both
react-native: 0.63.4
react-native-reanimated: 2.2.0
react-native-gesture-handler: 1.8.0

**Comment by MikhailVasiliev** [comment]
> I updated to version 3.0.5, but extraData is still not working:
> 
> ```
>     <DraggableFlatList
>       data={ this.state.data }
>       renderItem={ this.renderItem }
>       keyExtractor={(item, index) => `draggable-item-${item.id-index}`}
>       scrollPercent={5}
>       onDragEnd={({ data }) => this.onDragEnd(data)}
>       extraData={this.state.refresh}
>     />
> ```
> 
> refresh state will be updated when user changes the style of the list (short, detail, etc.) by pressing a button. using the same code, but switching to FlatList - extraData will be recognized.
> 
> Platform: both react-native: 0.63.4 react-native-reanimated: 2.2.0 react-native-gesture-handler: 1.8.0

Same to me, version 3.0.6, extraData still doesn't work

**Comment by xtrinch** [comment]
@computerjazz Doesn't work for me either.
