### ISSUE TITLE
Drag and drop doesn't work on Android 

### ISSUE THREAD

**Issue by gazedash** [computerjazz/react-native-draggable-flatlist#59]
react-native-draggable-flatlist version: 1.1.7
react-native version: 0.57.1

Drag and drop doesn't work on Android. The list just scrolls without dragging.

https://github.com/computerjazz/react-native-draggable-flatlist/issues/20

**Comment by kanthi0802** [comment]
Not working on iOS too

**Comment by gazedash** [comment]
@kanthi0802 works for me. Could you provide more info? Maybe code sample to be able to reproduce and fix it.

**Comment by kanthi0802** [comment]
@gazedash My bad it's working ! I have implemented it the wrong way. Working on Android too !

**Comment by gazedash** [comment]
@kanthi0802 do you mind sharing the code? Because for me drag and drop doesn't work on Android, how did you manage to solve it?

**Comment by computerjazz** [comment]
please try latest version (2.0.12 as of writing)and open a new issue if still broken. Be sure to follow all setup instructions for react-native-gesture-handler.
