### ISSUE TITLE
Releasing item without draging scrolls it to the top [v2]

### ISSUE THREAD

**Issue by webtaculars** [computerjazz/react-native-draggable-flatlist#87]
I am testing the [v2](https://github.com/computerjazz/react-native-draggable-flatlist/tree/v2) library. After releasing an element without dragging it, it scrolls to the top of the list. I am using ```react-native-reanimated@1.2.0```

Platform: Android

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11532969/64404188-bf9f3800-d098-11e9-82b4-29a2c2df8919.gif)

**Comment by computerjazz** [comment]
Thanks for the bug report! 

The hovering component was not properly setting its snap position in the case that it had not moved. This may be a reanimated bug, but I just pushed a fix to force the value to re-evaluate on every frame.

Please upgrade the package and let me know if it's still an issue.

**Comment by webtaculars** [comment]
It is fixed after upgrading the package. Thanks for the quick fix.

**Comment by adityahparikh** [comment]
Hey, I am using latest version of react-native-reanimated@1.7.0. I am still having this problem
